# Generated by Django 2.1.7 on 2019-04-28 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import games.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('state', models.CharField(choices=[(games.models.GameState('initial'), 'initial'), (games.models.GameState('preparing'), 'preparing'), (games.models.GameState('in_progress'), 'in_progress'), (games.models.GameState('finished'), 'finished')], default=games.models.GameState('initial'), max_length=15)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('finished', models.DateTimeField(blank=True, default=None)),
                ('current_question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Question')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='players.Player')),
                ('questions', models.ManyToManyField(default=None, related_name='game_questions', to='questions.Question')),
                ('winner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
