# Generated by Django 2.1.7 on 2019-04-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190428_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('initial', 'initial'), ('preparing', 'preparing'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='initial', max_length=15),
        ),
    ]
