# Generated by Django 2.1.7 on 2019-04-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190428_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
