# Generated by Django 2.1.7 on 2019-04-30 07:23

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('players', '0002_player_push_notification_token'),
        ('games', '0005_auto_20190428_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_a_time', models.DateTimeField(default=datetime.datetime.now)),
                ('player_b_time', models.DateTimeField(default=datetime.datetime.now)),
                ('question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Question')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='game',
            name='questions',
        ),
        migrations.AddField(
            model_name='game',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rounds',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='games.Round'),
        ),
    ]
