# Generated by Django 2.1.7 on 2019-04-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20190430_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rounds',
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rounds', to='games.Game'),
        ),
    ]
