# Generated by Django 2.1.7 on 2019-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='push_notification_token',
            field=models.CharField(blank=True, default=None, help_text='Expo push notification token', max_length=50, null=True),
        ),
    ]
